insert into public.employees (employee_id, employee_name, employee_email, state, designation, approval_email_level_1, approval_email_level_2, approval_email_level_3)
values
('NW0000023', 'Ravinder Jangili', 'ravinder.jangili@nxtwave.co.in', 'Telangana', 'State Business Head', NULL, NULL, 'mansoor@nxtwave.co.in'),
('NW0000744', 'Sreejish Mohana Kumar', 'sreejish.mohanakumar@nxtwave.co.in', 'Tamil Nadu, Kerala', 'State Business Head', NULL, NULL, 'mansoor@nxtwave.co.in'),
('NW0000137', 'Madugula Nagaraju', 'nagaraju.madugula@nxtwave.co.in', 'Andhra Pradesh', 'State Business Head', NULL, NULL, 'mansoor@nxtwave.co.in'),
('NW0000320', 'Mansoor Valli Gangupalli', 'mansoor@nxtwave.co.in', 'All States', 'Program Manager', NULL, 'mansoor@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0000737', 'Hari Haran S', 'hari.haran@nxtwave.co.in', 'Tamil Nadu', 'Area Business Head', 'sreejish.mohanakumar@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW0000943', 'Shashank Nanabala', 'shashank.n@nxtwave.co.in', 'All States', 'State Business Head', NULL, 'mansoor@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0001211', 'Satya Priya Dash', 'satyapriya.dash@nxtwave.co.in', 'Delhi NCR, West Bengal, Odisha, Rajasthan, Uttar Pradesh', 'Zonal Business Head', NULL, 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0001212', 'Arka Prabha Ghosh', 'arkaprabha.ghosh@nxtwave.co.in', 'Maharastra', 'State Business Head', NULL, 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0002084', 'Akshay Kumar Pal', 'akshaykumar.pal@nxtwave.co.in', 'Delhi NCR, Uttar Pradesh', 'State Business Head', NULL, 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0002151', 'Akutota Sanjay Kumar', 'sanjay.akutota@nxtwave.co.in', 'Telangana', 'Area Business Head', 'ravinder.jangili@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW0002147', 'Purella Akhil', 'purella.akhil@nxtwave.co.in', 'Telangana', 'Area Business Head', 'ravinder.jangili@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW0000282', 'Mutluri Yohan', 'yohan.mutluri@nxtwave.co.in', 'Andhra Pradesh', 'Student Relationship Officer', 'nagaraju.madugula@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW0002957', 'Sirigiri Kumar', 'sirigiri.kumar@nxtwave.co.in', 'Andhra Pradesh', 'Student Relationship Officer', 'nagaraju.madugula@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW0003002', 'Pakki Vinay', 'vinay.pakki@nxtwave.co.in', 'Andhra Pradesh', 'Student Relationship Officer', 'nagaraju.madugula@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW0003086', 'Pantrangam Vasu', 'pantrangam.vasu@nxtwave.co.in', 'Telangana', 'Student Relationship Officer', 'ravinder.jangili@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW0003236', 'Vignesh Shenoy', 'vignesh.shenoy@nxtwave.co.in', 'Karnataka', 'State Business Head', NULL, 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0003268', 'Raghu Acharya', 'raghu.s@nxtwave.co.in', 'Karnataka', 'Area Business Head', 'vignesh.shenoy@nxtwave.co.in', 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0003269', 'Attili Veera Bhadra Swamy', 'veerabhadraswamy.attili@nxtwave.co.in', 'Telangana', 'Student Relationship Officer', 'ravinder.jangili@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW0003261', 'Omkar Gundacharya', 'gundacharya.omkar@nxtwave.co.in', 'Karnataka', 'Area Business Head', 'vignesh.shenoy@nxtwave.co.in', 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0003316', 'Gajendra K', 'gajendra.k@nxtwave.co.in', 'Karnataka', 'Area Business Head', 'vignesh.shenoy@nxtwave.co.in', 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0003346', 'Mohammad Imran', 'mohammad.imran@nxtwave.co.in', 'Andhra Pradesh', 'Area Business Head', 'nagaraju.madugula@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW0003349', 'Matam Dinesh Babu', 'dineshbabu.matam@nxtwave.co.in', 'Karnataka', 'Area Business Head', 'vignesh.shenoy@nxtwave.co.in', 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0003384', 'Praveenkumar G V', 'praveenkumar.gv@nxtwave.co.in', 'Karnataka', 'Student Relationship Officer', 'vignesh.shenoy@nxtwave.co.in', 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0003379', 'Johnwesly G', 'johnwesly.g@nxtwave.co.in', 'Tamil Nadu', 'Student Relationship Officer', 'sreejish.mohanakumar@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW0003397', 'Mahesh B', 'mahesh.b@nxtwave.co.in', 'Karnataka', 'Student Relationship Officer', 'vignesh.shenoy@nxtwave.co.in', 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0003405', 'Narina Venkata Naga Chandramouli', 'chandramouli.narina@nxtwave.co.in', 'All States', 'Business Operation Associate', NULL, 'mansoor@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0003439', 'Narendran B', 'narendran.b@nxtwave.co.in', 'Tamil Nadu', 'Area Business Head', 'sreejish.mohanakumar@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW0002276', 'Adarsh Anand Digal', 'adarshanand.digal@nxtwave.co.in', 'Rajasthan', 'State Business Head', 'adarshanand.digal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0002277', 'Sambit Kumar Aich', 'sambitkumar.aich@nxtwave.co.in', 'Odisha', 'Area Business Head', 'anshuman.chatterjee@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0002078', 'Tibirisetty V L S Hari Santhosh', 'harisanthosh.tibirisetty@nxtwave.co.in', 'Karnataka, Maharastra', 'Zonal Business Head', NULL, 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0005086', 'Anshuman Chatterjee', 'anshuman.chatterjee@nxtwave.co.in', 'West Bengal, Odisha', 'State Business Head', NULL, 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0005277', 'Sivaranjith Sivakumar', 'sivaranjith.sivakumar@nxtwave.co.in', 'Tamil Nadu', 'Area Business Head', 'sreejish.mohanakumar@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW0005421', 'Vaibhav Sharma', 'vaibhav.sharma@nxtwave.co.in', 'Rajasthan', 'Area Business Head', 'adarshanand.digal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0005422', 'Gobind Ram Sharma', 'sharma.gobindram@nxtwave.co.in', 'Delhi NCR', 'Area Business Head', 'akshaykumar.pal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0005452', 'Ananth Lal S S', 'ananth.lal@nxtwave.co.in', 'Kerala', 'Area Business Head', 'sreejish.mohanakumar@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW0005424', 'Nikhil Kirtikumar Adhapure', 'nikhilkirtikumar.adhapure@nxtwave.co.in', 'Maharastra', 'Area Business Head', 'arkaprabha.ghosh@nxtwave.co.in', 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0005444', 'Rishabh Sharma', 'rishabh.sharma@nxtwave.co.in', 'Uttar Pradesh', 'Area Business Head', 'akshaykumar.pal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0005477', 'Sagar Kiran Bhure', 'sagarkiran.bhure@nxtwave.co.in', 'Maharastra', 'Area Business Head', 'arkaprabha.ghosh@nxtwave.co.in', 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0005488', 'Abhinav Pal', 'abhinav.pal@nxtwave.co.in', 'Uttar Pradesh', 'Area Business Head', 'akshaykumar.pal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0005573', 'Reshabh Singh', 'reshabh.singh@nxtwave.co.in', 'Uttar Pradesh', 'Area Business Head', 'akshaykumar.pal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0006124', 'Nitin Mahavir Jain', 'nitinmahavir.jain@nxtwave.co.in', 'Maharastra', 'Area Business Head', 'arkaprabha.ghosh@nxtwave.co.in', 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0006196', 'Ankur Hemant Akre', 'ankurhemant.akre@nxtwave.co.in', 'Maharastra', 'Area Business Head', 'arkaprabha.ghosh@nxtwave.co.in', 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0005701', 'Deekshith K S', 'deekshith.ks@nxtwave.co.in', 'Karnataka', 'Student Relationship Officer', 'vignesh.shenoy@nxtwave.co.in', 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0005703', 'Cn Madhusudan', 'madhusdan.cn@nxtwave.co.in', 'Karnataka', 'Student Relationship Officer', 'vignesh.shenoy@nxtwave.co.in', 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0005704', 'Akash N C', 'akash.nc@nxtwave.co.in', 'Karnataka', 'Student Relationship Officer', 'vignesh.shenoy@nxtwave.co.in', 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0005806', 'Nithin R', 'nithin.r@nxtwave.co.in', 'Karnataka', 'Student Relationship Officer', 'vignesh.shenoy@nxtwave.co.in', 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0005798', 'Ganisetti Chandra Kiran', 'ganisetti.chandrakiran@nxtwave.co.in', 'Andhra Pradesh', 'Student Relationship Officer', 'nagaraju.madugula@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW0005805', 'Mahmadhaniip Japharsab Chikkeri', 'mahmadhaniip.japharsabchikkeri@nxtwave.co.in', 'Karnataka', 'Student Relationship Officer', 'vignesh.shenoy@nxtwave.co.in', 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0005803', 'Gandi Prabhucharan', 'gandi.prabhucharan@nxtwave.co.in', 'Andhra Pradesh', 'Student Relationship Officer', 'nagaraju.madugula@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW0005451', 'Amlan Mishra', 'amlan.mishra@nxtwave.co.in', 'Odisha', 'Area Business Head', 'anshuman.chatterjee@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0005923', 'Badal Ranjan Rout', 'badalranjan.rout@nxtwave.co.in', 'Odisha', 'Student Relationship Officer', 'anshuman.chatterjee@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0005921', 'Pyush Saraf', 'pyush.saraf@nxtwave.co.in', 'Odisha', 'Student Relationship Officer', 'anshuman.chatterjee@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0005922', 'Sangram Haldar', 'sangram.haldar@nxtwave.co.in', 'Odisha', 'Student Relationship Officer', 'anshuman.chatterjee@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0005964', 'Shivam Srivastava', 'shivam.srivastava@nxtwave.co.in', 'Delhi NCR', 'Student Relationship Officer', 'akshaykumar.pal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0005967', 'Yogesh Kumar', 'yogesh.kumar@nxtwave.co.in', 'Delhi NCR', 'Student Relationship Officer', 'akshaykumar.pal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0006013', 'TheerthaKumar', 'theerthakumara.r@nxtwave.co.in', 'Karnataka', 'Student Relationship Officer', 'vignesh.shenoy@nxtwave.co.in', 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0006070', 'Prabhakaran S', 'prabhakaran.s@nxtwave.co.in', 'Tamil Nadu', 'Student Relationship Officer', 'sreejish.mohanakumar@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW0006110', 'Santhosh Sripalasetti', 'santhosh.sripalasetti@nxtwave.co.in', 'Andhra Pradesh', 'Student Relationship Officer', 'nagaraju.madugula@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW0006111', 'Galla Shyam Kalyan', 'shyamkalyan.galla@nxtwave.co.in', 'Telangana', 'Student Relationship Officer', 'ravinder.jangili@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW0006112', 'Abhay Kumar', 'abhay.kumar@nxtwave.co.in', 'Delhi NCR', 'Student Relationship Officer', 'akshaykumar.pal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0006184', 'Yogesh Sharma', 'yogesh.sharma@nxtwave.co.in', 'Rajasthan', 'Student Relationship Officer', 'adarshanand.digal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0006188', 'Ranjeet Khushlani', 'ranjeet.khushlani@nxtwave.co.in', 'Rajasthan', 'Student Relationship Officer', 'adarshanand.digal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0006238', 'Johnson K', 'k.johnson@nxtwave.co.in', 'Tamil Nadu', 'Student Relationship Officer', 'sreejish.mohanakumar@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW0006239', 'Bhanu Pratap Singh Sengar', 'bhanu.pratapsinghsengar@nxtwave.co.in', 'Rajasthan', 'Student Relationship Officer', 'adarshanand.digal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0006240', 'Shaik Abdul', 'shaik.abdul@nxtwave.co.in', 'Andhra Pradesh', 'Student Relationship Officer', 'nagaraju.madugula@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW0006291', 'Brijesh Sharma', 'brijesh.sharma@nxtwave.co.in', 'Rajasthan', 'Student Relationship Officer', 'adarshanand.digal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0006292', 'Shubham Santosh Raut', 'shubham.santoshraut@nxtwave.co.in', 'Maharastra', 'Student Relationship Officer', 'arkaprabha.ghosh@nxtwave.co.in', 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0006293', 'Aakash Bhagtani', 'aakash.bhagtani@nxtwave.co.in', 'Rajasthan', 'Student Relationship Officer', 'adarshanand.digal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0006324', 'Ajith Kumar S', 'ajithkumar.s@nxtwave.co.in', 'Tamil Nadu', 'Student Relationship Officer', 'sreejish.mohanakumar@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW0006325', 'Tauseef Ali', 'tauseef.ali@nxtwave.co.in', 'Uttar Pradesh', 'Student Relationship Officer', 'akshaykumar.pal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0006326', 'Ritik Kumar', 'ritik.kumar@nxtwave.co.in', 'Uttar Pradesh', 'Student Relationship Officer', 'akshaykumar.pal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0006328', 'Karthick H', 'karthick.h@nxtwave.co.in', 'Tamil Nadu', 'Student Relationship Officer', 'sreejish.mohanakumar@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW0006329', 'Mohd Fardeen Arif', 'mohdfardeen.arif@nxtwave.co.in', 'Uttar Pradesh', 'Student Relationship Officer', 'akshaykumar.pal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW1006426', 'Rohit Kumar Mishra', 'rohitkumar.mishra@nxtwave.co.in', 'Uttar Pradesh', 'Student Relationship Officer', 'akshaykumar.pal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW1006516', 'Shivam Gautam', 'shivam.gautam@nxtwave.co.in', 'Uttar Pradesh', 'Student Relationship Officer', 'akshaykumar.pal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW1006120', 'Kedem Ravi Teja', 'kedem.raviteja@nxtwave.co.in', 'Andhra Pradesh', 'Student Relationship Officer', 'nagaraju.madugula@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW1006256', 'Kushal Mukherjee', 'kushal.mukherjee@nxtwave.co.in', 'West Bengal', 'Student Relationship Officer', 'anshuman.chatterjee@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW1006296', 'Akshay E', 'akshay.e@nxtwave.co.in', 'Kerala', 'Student Relationship Officer', 'sreejish.mohanakumar@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW1006377', 'Muhammed Hijas', 'muhammed.hijas@nxtwave.co.in', 'Kerala', 'Student Relationship Officer', 'sreejish.mohanakumar@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW1006458', 'Rajagopal Vengatraman', 'rajagoapl.vengatraman@nxtwave.co.in', 'Tamil Nadu', 'Student Relationship Officer', 'sreejish.mohanakumar@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW1006514', 'Gokulakrishnan Muthaiya', 'gokulakrishnan.m@nxtwave.co.in', 'Tamil Nadu', 'Student Relationship Officer', 'sreejish.mohanakumar@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW1006529', 'Santhosh Kumar J', 'santhosh.kumarj@nxtwave.co.in', 'Tamil Nadu', 'Student Relationship Officer', 'sreejish.mohanakumar@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW1006532', 'Jithin Radhakrishnan', 'jithin.radhakrishnan@nxtwave.co.in', 'Kerala', 'Student Relationship Officer', 'sreejish.mohanakumar@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW1006533', 'Indraneel Ingole', 'indraneel.sanjayingole@nxtwave.co.in', 'Maharastra', 'Student Relationship Officer', 'arkaprabha.ghosh@nxtwave.co.in', 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW1006594', 'Sabarinathan', 'sabarinathan.s@nxtwave.co.in', 'Tamil Nadu', 'Student Relationship Officer', 'sreejish.mohanakumar@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW1006700', 'Venkat Kalyan Kolluri', 'venkatkalyan.kolluri@nxtwave.co.in', 'Telangana', 'Student Relationship Officer', 'ravinder.jangili@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW1006751', 'Tellakula Mohan Teja', 'tellakula.mohanteja@nxtwave.co.in', 'Telangana', 'Student Relationship Officer', 'ravinder.jangili@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW1006756', 'Mohamed Deenul Ajlan', 'mohamed.deenulajlan@nxtwave.co.in', 'Tamil Nadu', 'Student Relationship Officer', 'sreejish.mohanakumar@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW1006757', 'Anil Kumar Dhaked', 'anilkumar.dhaked@nxtwave.co.in', 'Rajasthan', 'Student Relationship Officer', 'adarshanand.digal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW1006758', 'Nanivarma Vm', 'nanivarma.vm@nxtwave.co.in', 'Karnataka', 'Student Relationship Officer', 'vignesh.shenoy@nxtwave.co.in', 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW1006938', 'Aryan Sharma', 'aryan.sharma@nxtwave.co.in', 'Rajasthan', 'Student Relationship Officer', 'adarshanand.digal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW1007046', 'Pankaj Madhukar Bhatkar', 'pankajmadhukar.bhatkar@nxtwave.co.in', 'Maharastra', 'Student Relationship Officer', 'arkaprabha.ghosh@nxtwave.co.in', 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW1007047', 'Akshay Anand', 'akshay.anand@nxtwave.co.in', 'Delhi NCR', 'Student Relationship Officer', 'akshaykumar.pal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW1007048', 'Ashish Patel', 'ashish.patel@nxtwave.co.in', 'Uttar Pradesh', 'Student Relationship Officer', 'akshaykumar.pal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW1007109', 'Ansar Basha', 'ansarbasha.hf@nxtwave.co.in', 'Karnataka', 'Student Relationship Officer', 'vignesh.shenoy@nxtwave.co.in', 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW1007110', 'Rajat Singh Bisen', 'rajatsingh.bisen@nxtwave.co.in', 'Uttar Pradesh', 'Student Relationship Officer', 'akshaykumar.pal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW1007111', 'Himanshu Badsiwal', 'himanshu.badsiwal@nxtwave.co.in', 'Delhi NCR', 'Student Relationship Officer', 'akshaykumar.pal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW1007156', 'Chethan Kumar R', 'chethankumar.r@nxtwave.co.in', 'Karnataka', 'Student Relationship Officer', 'vignesh.shenoy@nxtwave.co.in', 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0006012', 'Bhargav Raj Gv', 'bhargavraj.gv@nxtwave.co.in', 'Karnataka', 'Business Operation Associate', 'vignesh.shenoy@nxtwave.co.in', 'harisanthosh.tibirisetty@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0006181', 'Maddala Shanmukha Srinivasa Rahul Gupta', 'srinivasa.rahulgupta@nxtwave.co.in', 'Andhra Pradesh', 'Business Operation Associate', 'nagaraju.madugula@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW0006185', 'Syed Adnan Saleem', 'syed.adnansaleem@nxtwave.co.in', 'Telangana', 'Business Operation Associate', 'ravinder.jangili@nxtwave.co.in', NULL, 'mansoor@nxtwave.co.in'),
('NW0006186', 'Shekh Ali Mohammad', 'shekh.alimohammad@nxtwave.co.in', 'Delhi NCR', 'Business Operation Associate', 'akshaykumar.pal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0006187', 'Rishik Jaiswal', 'rishik.jaiswal@nxtwave.co.in', 'Uttar Pradesh', 'Business Operation Associate', 'akshaykumar.pal@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in'),
('NW0006327', 'Pratham Karan', 'pratham.karan@nxtwave.co.in', 'Odisha', 'Business Operation Associate', 'anshuman.chatterjee@nxtwave.co.in', 'satyapriya.dash@nxtwave.co.in', 'mansoor@nxtwave.co.in')
on conflict (employee_email)
do update set employee_id = excluded.employee_id, employee_name = excluded.employee_name, state = excluded.state, designation = excluded.designation, approval_email_level_1 = excluded.approval_email_level_1, approval_email_level_2 = excluded.approval_email_level_2, approval_email_level_3 = excluded.approval_email_level_3;
