-- ============================================================
-- Migration 124: Drop old text/enum columns (DEFERRED)
-- ============================================================
-- 
-- CRITICAL WARNING: ONLY execute AFTER:
-- 1. All backend code has been refactored to use ID columns
-- 2. All frontend code has been refactored
-- 3. All RLS policies have been rewritten to use ID columns
-- 4. ID-based system has been tested for 2+ weeks
-- 5. Backup tables (_backup_*) are confirmed intact
--
-- When ready, uncomment and run:
--
-- ALTER TABLE expense_claims DROP COLUMN IF EXISTS status;
-- ALTER TABLE expense_claims DROP COLUMN IF EXISTS work_location;
-- ALTER TABLE expense_claims DROP COLUMN IF EXISTS vehicle_type;
-- ALTER TABLE expense_claims DROP COLUMN IF EXISTS outstation_location;
-- ALTER TABLE expense_claims DROP COLUMN IF EXISTS from_city;
-- ALTER TABLE expense_claims DROP COLUMN IF EXISTS to_city;
-- ALTER TABLE approval_history DROP COLUMN IF EXISTS approver_email;
-- ALTER TABLE finance_actions DROP COLUMN IF EXISTS actor_email;
--
-- Also update RLS policies to use new ID columns before dropping.
