-- Migration 164 (formerly 023): Fix workflow RPCs — NO-OP
--
-- This migration originally fixed text-status-based workflow RPCs and backfilled
-- status_id. All of its changes were superseded by migrations 141–146 which
-- completely rewrote the status system to be ID-based and dropped the text
-- status column. Running the original SQL would fail because it references
-- columns/tables that no longer exist (expense_claims.status, resolve_status_id,
-- claim_transition_graph, etc.).
--
-- Kept as a placeholder to preserve migration numbering continuity.
SELECT 1;
